services:
  montisgal-events.mvc:
    image: montisgal-events.mvc
    build:
      context: .
      dockerfile: src/montisgal-events.mvc/Dockerfile
  montisgal-events-db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: montisgal_events
      MYSQL_USER: montisgal
      MYSQL_PASSWORD: montisgal
    ports:
      - "3306:3306"
    volumes:
      - montisgal-events-db:/var/lib/mysql
volumes:
  montisgal-events-db: