version: '3.1'

services:
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: montisgal_events_api
      MYSQL_USER: montisgal
      MYSQL_PASSWORD: montisgal
    ports:
      - "3306:3306"
    volumes:
      - montisgal-events-api-db:/var/lib/mysql

volumes:
  montisgal-events-api-db: